### ISSUE TITLE
Spring 2017 Meeting #8 (Monday, 04/03, 3-4pm, McK B0228)

### ISSUE THREAD

**Issue by 23koivisto** [umd-coding-workshop/website#178]
#Algorithms & their others: Algorithmic culture in context -- Paul Dourish -- http://journals.sagepub.com/doi/abs/10.1177/2053951716665128

Notes from Critlib unconference session on critical theory & tech in libraries (look for session 3) -- https://docs.google.com/document/d/19qvL8q607XsEPdRJcFG3OCLJ76OriAKEda0QcBxVwSo/edit

**Comment by peichman-umd** [comment]
[Computerphile on YouTube](https://www.youtube.com/user/Computerphile)

This series spun out from [Numberphile](http://numberphile.com/), which in turn spun out from [Sixty Symbols](http://sixtysymbols.com/).

**Comment by 23koivisto** [comment]
Finn Brunton's "Spam: A Shadow History of the Internet" — https://www.amazon.com/Spam-Shadow-History-Internet-Infrastructures/dp/026252757X
