### ISSUE TITLE
Fall 2018 Meeting #3 (Friday, 09/14, 3:00-4:00pm, McK B0228)

### ISSUE THREAD

**Issue by jwestgard** [umd-coding-workshop/website#239]
[HEADNOTE: Please note the new day (Friday)]
# Agenda
- Announcements

**Comment by 23koivisto** [comment]
Been seeing a lot of chatter about Google Data Search (see included email below pointing out some critical perspectives on the service).  Perhaps this would be something worth discussing.

>I shared this response on the ACRL STS list as well. While this is a great step towards increasingly visibility of datasets, these Twitter threads help explain where some potentially underdeveloped functionality remains in this search interface and where there are other data search options:
>
><https://twitter.com/AWhitTwit/status/1037463720920670208>
>
><https://twitter.com/danbri/status/1037492072582991872>
>
>I thought these were important perspectives to consider as they may inform one’s use of these resources.
>
>Yasmeen
